export default Object.freeze({
    //GLOBAL TYPES
    SET_LOADING: 'SET_LOADING',
    SET_SUCCSSES_MESSAGE: 'SET_SUCCSSES_MESSAGE',
    SET_ERRORMESSAGE: 'SET_ERRORMESSAGE',

    //TODO TYPES
    RESET_TODO_STATE: 'RESET_STATE',
    MARKED_TASKS: 'MARKED_TASKS',
    MARK_ALL_TASKS: 'MARK_ALL_TASKS',
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    TOGGLE_CONFIRM_MODAL: 'TOGGLE_CONFIRM_MODAL',
    OPEN_EDIT_TASK_MODAL: 'OPEN_EDIT_TASK_MODAL',
    REMOVE_MARKED_TASKS: 'REMOVE_MARKED_TASKS',
    ADD_TASK: 'ADD_TASK',
    REMOVE_TASK: 'REMOVE_TASK',
    GET_TASK: 'GET_TASK',
    EDIT_TASK: 'EDIT_TASK',
    //SINGLETASK TYPES
    RESET_SINGLETASK_STATE: 'RESET_SINGLETASK_STATE',
    EDIT_SINGLETASK: 'EDIT_SINGLETASK',
    CLOSE_SINGLETASK_MODAL: 'CLOSE_SINGLETASK_MODAL',
    //CONTACTFORM TYPES
    HANDLE_CHANGE: 'HANDLE_CHANGE',
    RESET_CONTACTFORM_STATE: 'RESET_CONTACTFORM_STATE',
    //ADDMODAL TYPES
    GET_EDIT_TASK: 'GET_EDIT_TASK',
    SET_DATE: 'SET_DATE',
    HANDLE_CHANGE_MODAL: 'HANDLE_CHANGE_MODAL',
    RESET_MODAL_STATE: 'RESET_MODAL_STATE',

    //SEARCH TYPES
    SEARCH_ON_CHANGE: 'SEARCH_ON_CHANGE',
    DROP_DOWN_ONCHANGE: 'DROP_DOWN_ONCHANGE',
    SET_SEARCH_DATE: 'SET_SEARCH_DATE',
    RESET_SEARCH_STATE: 'RESET_SEARCH_STATE'
});